dist: xenial
language: python

cache: pip

matrix:
  include:
    - name: "Python 3.7 on Xenial"
      python: 3.7
      dist: xenial
    - name: "Python 3.7 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install: choco install python
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

install:
  - pip3 install -U -r dev-requirements.txt

script:
  # python -m appends current path to PYTHONPATH, pytest would not find app.model
  # it's important to use absolute paths in test files for both files and modules
  - python -m pytest

after_success:
  - codecov